### ISSUE TITLE
UNSAFE_componentWillReceiveProps console error

### ISSUE THREAD

**Issue by adi518** [asabaylus/react-command-palette#804] opened 2021-07-11 00:00 UTC
**Describe the bug**
Deprecated lifecycle console error. It seems like some dependency components may need upgrading.

**To Reproduce**
Open the palette.

**Expected behavior**
No errors in console.

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser Chrome
 - Version 91.0.4472.114 

**Additional context**
```js
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: Autosuggest, Autowhatever
```

That leads to a `react-autosuggest` issue: https://github.com/moroshko/react-autosuggest/issues/624. Apparently fixed and merged (https://github.com/moroshko/react-autosuggest/pull/681), but seems like they haven't released a new version since then. I'll leave this issue open until they release the fix. In case they release it and you don't want to wait for a new release from this package, use the `resolve` option in `package.json` to resolve the new version.

**Comment by asabaylus** [comment] 2021-07-22 11:43
@adi518 I've created a [simple example](https://codesandbox.io/s/reactcommandpalette-t1lyh?file=/src/commands.js) you can reference. Please note that I cannot reproduce your issue. Can you publish an example of your code that cause the error message?

**Comment by asabaylus** [comment] 2021-07-27 01:34
Closing unable to reproduce

**Closed by asabaylus** 2021-07-27 01:34 UTC
Labels: bug

**Comment by adi518** [comment] 2021-07-27 10:33
Sorry for the delayed response.

> @adi518 react-command-palette is on [react-autosuggest v10.0.1](https://github.com/asabaylus/react-command-palette/blob/main/package.json#L82). I've been unable to reproduce your error, we can continue to troubleshoot you issue outside this repo

I realized what the actual issue is. I'm using React 17 in strict mode, so that issue is not really relevant. As for the `react-autosuggest` version. Their latest version is `10.1.0`. GitHub collapses the last three releases, so you can miss it. I'm not saying it will fix it (it won't), but might consider upgrading to latest.

The relevant `react-autosuggest` issue is this: https://github.com/moroshko/react-autosuggest/issues/624. Probably applicable to `react-autowhatever` as well.

**Comment by asabaylus** [comment] 2021-08-31 12:45
@adi518 I routinely update all dependencies. As soon as the react-autosuggest team pushes a fix I’ll bump my package.json. There will be a new issue for that so I’ll leave this closed for now. Thanks for the update.
